version: '3.4'

services:

  user.api:
    image: ${REGISTRY:-konbilocker}/user.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: aspnet-core-user-management/Dockerfile

  order.api:
    image: ${REGISTRY:-konbilocker}/order.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: konbini-api-v2/Dockerfile
    depends_on:
      - user.api

  order.customerui:
    image: ${REGISTRY:-konbilocker}/order.customerui:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: LockerPreorder/Dockerfile
    depends_on:
      - user.api
      - order.api

   order.backendui:
    image: ${REGISTRY:-konbilocker}/order.backendui:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: tablet/Dockerfile
    depends_on:
      - user.api
      - order.api